# Generated by Django 5.2.4 on 2025-08-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='bag_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
